export * from './login/LoginPage'
export * from './signup/SignupPage'
export * from './aules/AulesPage'
export * from './loginAlumne/LoginAlumnePage'
export * from './crearTest/CrearTestPage'
export * from './respondreTest/RespondreTestPage'
export * from './resultatsTest/ResultatsTestPage'
